sudo: required

language: clojure

jdk:
  - openjdk8

services:
  - docker

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "HGiJKPGAcG9L0NnquG2SI79d7YIdSxuKOx8MGcag5ikHk1lTxibe0jCfFfkk25tIECvIf3QfOxK+gpsRqk2ARB6K8VfaygQ13eahYD8RM6GjUohUJ2XoBBZSz5+v05HVgPd0uGrlkrno9L8672MnQvQ3QXEJHdBsXJOzcdEIUWphTRqEi1a6p+bSMcIP3Hz+lfd1HHrTHlJ/cj1KNmYrLdTzRWy8TChcxmNA9Xphm9ZGKb2IQf3nJ68VN6ozmzzsbZjz4loHwiLUS/Vh0giqThVKzx5lyC5iuxwM2WYEB+g4+yFql5JcExCQFVEZKNVadk2D2z1EhwaEUAs/iS8o27g482ryb+Mw7PX4SAH4uUbKwzSs7p2Frrl+ptBmi20BI6EUO9xzaWuZ7jXN4K++cb7OmMfe8GPvCgThIsHJ37q4v5wN2s1sspqkkIVivSWoD+/u1Mp52LpB0lMusGw9nlCrJwuMA5Zc4aU1BiCKvokIhknepB43/ZUnC7CaKCPLSL66p8lfIqb4Zz5n3h2hD8XJ+7Dn7M37ClvFmkuJj6rlccVXzPULz9Tb3Ou6BBAfRJcqDx+42pHdoXKWahn4BWqHLMvpwXWNoTDtbDTGeVTMtA1fX1+2Rgbuypw+gAYO6CBmijJ9E6hd4wFGwEM+oxx17fmgESSE1N5I1L6JZXg="
    # AWS_SECRET_ACCESS_KEY
    - secure: "RuCKuJ1baWE3c5Pp5ZYe4QBJv11u1KKPFGKHwrIKzqKLsQQio3z2ATn/iQoqN05xUNGvsJR2aHesL+xtnYlHCLwUtqdd3CdxDEP4a0zXFvbWHOSyrYz3llxOiSkL/NXcBLYCGUnasyMCELwQzk8DoDgUCzeBMbuw2hsLqLx6DxRyt+AkZGDWA9HAytNgOJ4y5rlJ+665ULUxqOY3fWNhkruSoz+pkFdcDJJ1OzWK75RfNMKG9uyQR2lJgsIBpqIVDJXi67gAZB7Ihyg/aO6CFsy+82P7o87jzrHnyLqspF7QjtmbNEXRLAAKX31E2/LNQafw01yOSWswRVgvfxC17HQzegqXcK/Mu8EAvMyV6qokt81bBcg4/5eiTgZfZhlHLsafw5gf5sGTiNERKNO4DuQGXLUZH8ubHkYpSYWSB8DqS+T5nPZ2c83owRDYdmaWE6xXuwCdlDNgZA2dCOnHafsK8WX4yd8dL3m6ZenvMuQj1CTmisOzXMvWsNIp6mYNtzGNeEtM+U+ps0m700oCPIzD/zHkTr1VLlsCLoCMKh4G7NXoGUyD0z8WqLQtURKF02EjWhQe+7q21lJOi08QnBpbGW5lEgeiOLakbrbJB4mXy8jPx2n+mPOCsfXKGP3kW01D0VunT3jEa8dqEPKbp9HaFjzqjN2A77J+pRkE7UU="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="ulkoiset-rajapinnat"

script:
  - lein -U test
  - lein uberjar

  - mv target/ulkoiset-rajapinnat-0.1.0-SNAPSHOT-standalone.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
  - cp -vr oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-fatjar-openjdk8:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh ${ARTIFACT_NAME}

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh ${ARTIFACT_NAME}
  on:
    all_branches: true

cache:
  directories:
  - $HOME/.m2
